export const listReport = [
    'Minor safety',
    'Nudity and sexual content',
    'Regulated goods and activities',
    'Misinformation',
    'Shocking and graphic content',
    'Frauds and scams',
    'Hate and harassment',
    'Violence, abuse, and criminal exploitation',
    'Suicide and self-harm',
    'Disordered eating and unheathy body image',
    'Dangerous activities and challenges',
    'Deceptive behavior and spam',
    'Sharing personal information',
    'Other',
];
